const fs = require('fs')
const content = [
  "'use client'",
  "import { useState } from 'react'",
  "",
  "export default function ResearchInterface() {",
  "  const [query, setQuery] = useState('')",
  "  const [loading, setLoading] = useState(false)",
  "  const [answer, setAnswer] = useState('')",
  "  const [results, setResults] = useState<any[]>([])",
  "",
  "  const search = async () => {",
  "    if (!query.trim() || loading) return",
  "    setLoading(true)",
  "    try {",
  "      const res = await fetch('/api/research', {",
  "        method: 'POST',",
  "        headers: { 'Content-Type': 'application/json' },",
  "        body: JSON.stringify({ query }),",
  "      })",
  "      const data = await res.json()",
  "      setAnswer(data.answer || '')",
  "      setResults(data.results || [])",
  "    } catch { setAnswer('Error') } finally { setLoading(false) }",
  "  }",
  "",
  "  return (",
  "    <div className='p-4'>",
  "      <div className='flex gap-3 mb-4'>",
  "        <input type='text' value={query} onChange={e => setQuery(e.target.value)}",
  "          onKeyDown={e => e.key === 'Enter' && search()}",
  "          placeholder='Research anything...'",
  "          className='flex-1 border rounded-2xl px-4 py-3 text-sm outline-none' />",
  "        <button onClick={search} disabled={!query.trim() || loading}",
  "          className='bg-cyan-500 text-white px-6 rounded-2xl text-sm'>",
  "          {loading ? 'Searching...' : 'Search'}",
  "        </button>",
  "      </div>",
  "      {answer && <div className='bg-cyan-50 rounded-2xl p-4 mb-4'><p className='text-sm'>{answer}</p></div>}",
  "      {results.map((r, i) => (",
  "        <a key={i} href={r.url} target='_blank' rel='noopener noreferrer'",
  "          className='block border rounded-2xl p-4 mb-2'>",
  "          <p className='text-sm font-semibold'>{r.title}</p>",
  "          <p className='text-xs text-gray-500'>{r.content}</p>",
  "        </a>",
  "      ))}",
  "    </div>",
  "  )",
  "}",
].join('\n')

fs.writeFileSync('components/research/ResearchInterface.tsx', content)
console.log('Done')