const fs = require('fs')
const content = [
  "'use client'",
  "import { useState } from 'react'",
  "import { signIn } from 'next-auth/react'",
  "import { useRouter } from 'next/navigation'",
  "",
  "export default function LoginPage() {",
  "  const router = useRouter()",
  "  const [email, setEmail] = useState('')",
  "  const [password, setPassword] = useState('')",
  "  const [loading, setLoading] = useState(false)",
  "  const [error, setError] = useState('')",
  "",
  "  const handleSubmit = async (e: React.FormEvent) => {",
  "    e.preventDefault()",
  "    setLoading(true)",
  "    setError('')",
  "    const res = await signIn('credentials', { email, password, redirect: false })",
  "    if (res?.ok) {",
  "      router.push('/dashboard')",
  "    } else {",
  "      setError('Invalid email or password.')",
  "      setLoading(false)",
  "    }",
  "  }",
  "",
  "  return (",
  "    <main className='min-h-screen bg-gray-50 flex items-center justify-center px-4'>",
  "      <div className='w-full max-w-md'>",
  "        <h1 className='text-4xl font-bold text-center text-gray-900 mb-2'>MIKKAL</h1>",
  "        <p className='text-center text-gray-400 text-sm mb-8'>WISDOM · INSIGHT · INTELLIGENCE</p>",
  "        <form onSubmit={handleSubmit} className='bg-white rounded-2xl p-8 shadow-sm'>",
  "          <h2 className='text-lg font-semibold text-gray-900 mb-6 text-center'>SIGN IN</h2>",
  "          {error && <p className='text-red-500 text-sm mb-4 text-center'>{error}</p>}",
  "          <div className='mb-4'>",
  "            <label className='block text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide'>Email</label>",
  "            <input type='email' value={email} onChange={e => setEmail(e.target.value)} required",
  "              className='w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-cyan-400' />",
  "          </div>",
  "          <div className='mb-6'>",
  "            <label className='block text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide'>Password</label>",
  "            <input type='password' value={password} onChange={e => setPassword(e.target.value)} required",
  "              className='w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-cyan-400' />",
  "          </div>",
  "          <button type='submit' disabled={loading}",
  "            className='w-full bg-cyan-500 hover:bg-cyan-600 text-white py-3 rounded-xl text-sm font-semibold transition-colors disabled:opacity-50'>",
  "            {loading ? 'Signing in...' : 'ENTER MIKKAL'}",
  "          </button>",
  "        </form>",
  "      </div>",
  "    </main>",
  "  )",
  "}",
].join('\n')

fs.writeFileSync('app/login/page.tsx', content)
console.log('Done')